version: 2.1
      
jobs:
  my1stjob:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: hello world
          echo "hello world"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test

workflows:
  my-1st-workflow:
    jobs:
      - my1stjob
